### PR TITLE
Zeit deploys

### PR DESCRIPTION
**Pull request by ssskram**
### Radix, meet Zeit

I've configured CD for this site using Zeit's new [advanced project settings](https://zeit.co/blog/advanced-project-settings).  Every commit deploys a preview, and every merge to master deploys to production.

To facilitate the `website` directory building as a standalone resource, I added an empty component at `website/src/pages/index.js`.  After a couple hours of troubleshooting, introducing this dummy component was the only way I could get `gatsby build` to generate the `index.html` necessary to deploy this site properly.  My work with gatsby is minimal, so if I'm missing something here do share!

~~Also, just to be clear, we're not taking down the Netlify service right now, or affecting the existing hosting setup in any way.    We're just getting Zeit hosting & CD configured for when we do switch over to Zeit for DNS & static sites, which will happen in the next week or two.~~

The Zeit service is now live, so we need to merge this into master before you do another release (or else the Zeit deployment will fail.)

### CODE REVIEW

**Comment by ssskram** [comment]
PS ignore the Zeit build failure 👇 .  Was from the unsuccessful git integration.

**Comment by ssskram** [comment]
PPS, if you're cool with this configuration, we can also potentially use a Github action to execute the yarn scripts on PR, merge, etc.

**Comment by peduarte** [comment]
@ssskram Thanks for this. Can I turn off Netlify?

**Comment by ssskram** [comment]
@peduarte  Sure can!

**Pull request merged**
