### PR TITLE
Icon Button and the new Button variant “ghost”

### LINKED ISSUE #192: GhostButton needs a bigger size variant
We used to have a bigger size for GhostButton, but [was removed here](https://github.com/modulz/radix/pull/175/files#diff-1c398bdf10383c999cbf7c4351404205)

We need to add this back so we can render 25px Icons in them 👍

### PR DESCRIPTION
**Pull request by vladmoroz**
- Renames Ghost Button → Icon Button
  - All typographic properties are removed from this component
  - The component can be used consistently with any icon size. Closes #192.
- Adds `variant="ghost"` to the Button component
  - Inline with other components that have `variant="ghost"`, like Input, Select, Card
  - Replaces previous Ghost Button with text usage
  - Works on different backgrounds

### CODE REVIEW

**Comment by peduarte** [comment]
Can you update the Button docs example section, the one under “colours” to include this one?

**Comment by vladmoroz** [comment]
@peduarte thanks for the catch, updated 👌

**Comment by peduarte** [comment]
Perfect thanks. Merge when ready. You might wanna liaise with @benoitgrelard about the releases and updating Modulz, as it has breaking changes. 

Once it’s release put a little reminder on Slack so I can update the marketing site too. 

Thanks!

**Comment by vladmoroz** [comment]
Sure, I'll check with Benoit first then.

Speaking of merging things, can't get to merge this one even though it's approved.

**Comment by peduarte** [comment]
I’ll change the settings now and give you POWER!

**Comment by benoitgrelard** [comment]
Ok, I'll merge all these now and if that's ok with you both I'll coordinate the next release when time is good.

**Pull request merged**
