### PR TITLE
separation of logic layers and applying declarative approach

### PR DESCRIPTION
**Pull request by grzim**
separation of logic layers - data describing component styles are independent of the logic applying platform-specific structure. Such an approach removes all repeated sequences in the structure and makes codebase clearer. Every component could have its own folder with different files for react logic, storybook, and style data.
It gives also flexibility - makes it possible to use the same stylings to WebComponents and even Angular/Vue Components (both should have their own adapters, only a sketch included). Thanks to this, radix could be far more powerful.

### CODE REVIEW

**Comment by peduarte** [comment]
@grzim Hey 👋 

Very interesting. Thanks for taking the time to propose this 🙏 

I love the idea of being able to decouple styles to framework but the way I see it is that most of this work would happen in the Primitives library. 

I'll close this PR since it's outside the scope of our current roadmap. This hand-written version of Radix will be replaced by a [Modulz](https://modulz.app) generated one.

Thanks again for suggesting this.

**Comment by grzim** [comment]
Sure,
is the roadmap available somewhere?

**Comment by peduarte** [comment]
@grzim No, it's internal to the Modulz team. But basically, our next step is to migrate Radix into Modulz, and have it completely designed, maintained and deployed from Modulz. 

Once this is done, this repo will be archived. 

Modulz will eventually export to Vue, Svelte, Angular, vanilla, etc. but these efforts will happen in the product side of things.

Does that make sense?

**Comment by grzim** [comment]
And what is your approach - you want to make Modulz as a tool to generate react components, that later can be translated to other languages, or make Modulz as a tool for describing abstraction that later can be applied to different view libraries/frameworks with library-specific adapters?

**Comment by peduarte** [comment]
Modulz is not so much about "generating React components". Modulz is more about styling. It's a design tool which takes the styles from users and applies them to pre-built components. These pre-built components currently only exist in React, but the goal is to have a version in each popular framework. 

The styles from Modulz are already framework/library agnostic, it's expressed as a data structure that we can parse however we want.

**Comment by grzim** [comment]
It is exactly what I was asking about. I like the idea of making framework-agnostic data structures - a separation between business logic and platform logic. Basically it was what I was trying to introduce in my pull request.

It's a very interesting project.

**Pull request closed without merging**
