### PR TITLE
chore(radix-icons): use rollup

### PR DESCRIPTION
**Pull request by stevenbenisek**
:construction_worker: use Rollup and rollup-plugin-typescript2
:package: align package main and module with radix (avoids declaration files in
the root)
:racehorse: reduce build time to ~34s

**Note**: doesn't generate development bundles (tsdx build did, but doesn't seem to be used anywhere)

#122

### CODE REVIEW

**Comment by peduarte** [comment]
@stevenbenisek Hey, thanks for this 👍 

@loklaan Could you take a  👀 please?

**Comment by colmtuite** [comment]
Thanks @stevenbenisek :)

**Comment by loklaan** [comment]
Thanks @stevenbenisek!

Are you using the icon set for anything?

---

@peduarte We were going to wait for radix to stabilise, as well as the completion of the icon set, before refactoring the build tooling. I'm still for that, but wouldn't mind merging this in the next time we add to the icon set; I'd need to test the exported code for correct meta fields (`__esModule` etc)

**Comment by peduarte** [comment]
@loklaan yeah good point, a lot going on at the moment — if you think it’s a good time to merge this, go ahead (as long as everything still works as expected). 

We can always revisit later. 

In any case, your call 👍

**Comment by stevenbenisek** [comment]
@loklaan No, I'm not using the icon set. I was just curious about the project. Poked around a bit. Created the PR while I was at it 😃

**Comment by loklaan** [comment]
@stevenbenisek Oh nice, well thank you anyway! I was asking to see if you would have wanted this PR merged sooner than later. As it stands though it'll get tested & merged the next time someone adds to the icon set. 👍

**Comment by peduarte** [comment]
I've moved all icon related work to it's own repo: https://github.com/modulz/radix-icons

Thanks for this, I'll probably implement these changes over there in the future.

**Pull request closed without merging**
