### PR TITLE
Implement Table Primitive

### LINKED ISSUE #207: Implement Primitives Table
Let's talk design @vladmoroz @colmtuite 🌈

### PR DESCRIPTION
**Pull request by peduarte**
Closes #207 

image

### CODE REVIEW

**Comment by benoitgrelard** [comment]
Sorry one thing, when I look at the preview link I don't see docs for the Table, is the mdx file for it missing?

**Comment by peduarte** [comment]
Docs on the way

**Comment by vladmoroz** [comment]
> Just a thought for later for us to consider, for compound components like these, it might make sense to hang off all the part exports off of the main component like:

Please 👏👏👏

**Comment by peduarte** [comment]
hehe, easy now lads 😄

**Pull request merged**
