### PR TITLE
Import @modulz/radix-icons

### PR DESCRIPTION
**Pull request by loklaan**
_Includes the private `@modulz/generate-icon-lib` package._

## Summary

All but the two last commits were cleanly imported from modulz/radix-icons.

Please have a look at the changes made in the last commit, as I added commitlint etc. 👍 

Closes: modulz/core#257

### CODE REVIEW

**Comment by peduarte** [comment]
Nice one ✌️ 

Gonna checkout the branch and test it properly.

First question I have is regarding the commitlint addition:
- Is this set up for all packages? How does it work exactly?

Thanks!

**Comment by peduarte** [comment]
Nice one ✌️ 

Gonna checkout the branch and test it properly.

First question I have is regarding the commitlint addition:
- Is this set up for all packages? How does it work exactly?

Thanks!

**Comment by loklaan** [comment]
@peduarte Hope you had a chance to check it out!

* Yup it's setup for the monorepo
* Backing reason is we wanna [generate changelogs](https://github.com/conventional-changelog/conventional-changelog), and in a monorepo that is hard unless [rules](https://www.conventionalcommits.org) are applied to commit messages
* The `commitlint` tool will run on a git hook, and test it generally for:
  * The pattern: `type(scope?): description` (the body of the summary can be whatever)
    * The `type` describes what kind of semver change we expect to have made.  
      _build, ci, chore, docs, feat, fix, perf, refactor, revert, style, test_
    * The `scope` is technically optional but this is where we mention the package, eg. `@modulz/radix` (we may drop the `@modulz` to save characters, but unsure). No scope needed for top level monorepo code management stuff.
    * The `description` is a well written, succinct and [imperative](https://chris.beams.io/posts/git-commit/#imperative) summary
  * The length of the lines (fairly limited but makes for an easy to read log)

**Comment by peduarte** [comment]
@loklaan cool, does this affect the release flow?

Or is it still `yarn release` then choosing the version?

**Comment by loklaan** [comment]
@peduarte No all commands can still hide under that script; we may just add `--conventional-commits`.

Gotta do another icon release, and it looks like you're across and ok with the additions to the top level stuff, so I'm going to merge this PR. Hit me up if you want any changes later though!

**Comment by loklaan** [comment]
Rebased on latest `master`

**Comment by peduarte** [comment]
Daaaamn my bad, I should've asked to hold off merging this for a bit. I haven't had a chance to do a proper test since this week I'm knee-deep implementing Radix into Core and therefore making many alpha releases with changes needed.

All good though, I'll take a good look now.

**Pull request merged**
